### PR TITLE
Deploy to Netlify

### LINKED ISSUE #26: Links to sample data cause a 404
A community user reported the following via private gist.

There's links to sample data from the docs that currently result in a 404. For instance, the one linked from the section https://zed.brimdata.io/docs/next/tutorials/zed/#adding-data-to-our-lake highlighted here:

image

When clicked:

image

It doesn't fail when clicked in the page's original location within section https://github.com/brimdata/zed/blob/main/docs/tutorials/zed.md#adding-data-to-our-lake on GitHub, however. The original markdown link is just `[here](github1.zng)`, and when clicked from within GitHub that resolves to https://github.com/brimdata/zed/blob/main/docs/tutorials/github1.zng. For what it's worth, that may not be a great link destination either, because it just brings the user to a page at https://github.com/brimdata/zed/blob/main/docs/tutorials/github1.zng that looks like this:

image

At this point clicking either "View Raw" or that "Download" button both end up downloading the file. So having this link resolve to the intermediate screen doesn't seem to be helping the user much.

Meanwhile, on the deployed docs website, the hyperlink that 404s ends up as https://zed.brimdata.io/assets/files/github1-2496d524ce44f4cb9f32cfeb70fa669e.zng/. Based on what I see in the [Docusaurus docs](https://docusaurus.io/assets/files/docusaurus-asset-example-93ea653de6d8636f7254aecab1adbcce.docx), I guess it recognizes it's a file destination and downloads it and serves it out of this `assets/` directory. In any case, as it turns out, if we just remove the trailing slash, the link works fine as https://zed.brimdata.io/assets/files/github1-2496d524ce44f4cb9f32cfeb70fa669e.zng.

Therefore, I can see see at least two possible ways out, though I'm sure there's others:

1. We could change the destination for the link in the original markdown to be https://github.com/brimdata/zed/raw/main/docs/tutorials/github1.zng (i.e., the link attached to that "Download" button), since it looks like that link would stay as-is even after Docusaurus publishes the site. This would have the added bonus that if users ever click the link in the original page on GitHub it'll go straight to download, but maybe there's other negatives to having an absolute URL like that.

2. Someone could figure out how to remove the trailing slash from the generated link on the docs site or figure out how to make our web site serve a file destination even if it has a trailing slash. FWIW, I did some searching and found people at https://github.com/facebook/docusaurus/issues/6282 talking about a similar problem.

### LINKED ISSUE #28: Add a link checker
I recently realized the deployed docs site could benefit from an automated link checker, since this would find issues like #26, i.e.,  links that are fine when browsing the docs within GitHub but then break after being deployed to https://zed.brimdata.io/.

I've started running some tests using the same [ruzickap/action-my-broken-link-checker](https://github.com/ruzickap/action-my-broken-link-checker) that's currently used on the brimdata.io web site. In addition to flagging the #26 errors, it also uncovered new issues #27 and the broken links being fixed in https://github.com/brimdata/zed/pull/4028.

Once we've got those and any other issues addressed such that the link checker passes cleanly on the deployed site, I'll add that Action to the Workflows in this repo so it always runs and notifies us of new breakages as they occur.

### PR DESCRIPTION
**Pull request by philrz**
## Summary

Researching a fix for #26 taught us that GitHub Pages is probably not a great destination for the Docusaurus-based Zed docs site. The tl;dr is that the default Docusaurus `trailingSlash: true` config caused HTTP 404 errors on the asset links for sample ZNG data referenced from the [Zed tutorial](https://zed.brimdata.io/docs/tutorials/zed/), and an attempt to fix that by using an alternate `trailingSlash: false` config in Docusaurus caused a different failure as described in #32.

The table at https://github.com/slorber/trailing-slash-guide gives a nice summary to not only confirm what we saw with GitHub Pages but also points at a Netlify config that should work fine instead. The changes in this PR are a move to that Netlify config.

image

I've created a new Netlify account attached to docs@brimdata.io that's currently hosting a test deployment of the docs site at https://stellar-lebkuchen-6a326d.netlify.app. If this PR is approved, I'll proceed with the **Final Steps** list at the bottom of this PR text so that [zed.brimdata.io](https://zed.brimdata.io/) will ultimately point at the Netlify site going forward.

Fixes #26
Fixes #28

## Limits/Cost

We're currently using the free Netlify "Starter" level, which gives us a bandwidth allotment of 100 GB/mo. The next level up is "Pro" at $19/mo which provides bandwidth of 1 TB/mo. As I'm not sure just how much traffic the site gets, I'll plan to keep an eye on the bandwidth utilization and if the daily rate of increase puts us anywhere near danger of hitting the 100 GB/mo ceiling, we can start paying.

## DNS Config Deltas

I've created a temporary CNAME in our Google Cloud DNS settings to point [testzed.brimdata.io](https://testzed.brimdata.io/) at [stellar-lebkuchen-6a326d.netlify.app](https://stellar-lebkuchen-6a326d.netlify.app/) for the purposes of test & review of this PR. Once this PR is approved, the CNAME for zed.brimdata.io will be modified to point to stellar-lebkuchen-6a326d.netlify.app.

## Netlify Config Deltas

I confirmed that simply moving the docs site in its current state to Netlify with out-of-the-box default Netlify config does make it such that the asset links no longer HTTP 404. However, as also indicated by the table above and at https://docusaurus.io/docs/deployment#deploying-to-netlify, hitting the URLs with `curl` showed some "unnecessary redirects" happening behind the scenes. E.g., this is an HTTP 200:

```
$ curl -I https://stellar-lebkuchen-6a326d.netlify.app/docs/commands/zed/
HTTP/2 200 
```

...but if someone were to hit this _without_ the trailing slash, there's an HTTP 301 hop:

```
$ curl -I https://stellar-lebkuchen-6a326d.netlify.app/docs/commands/zed
HTTP/2 301 
```

Based on the advice from that Docusaurus link above, that led me to modify the Netlify config at **Site Settings > Build & Deploy > Asset Optimization** from this default:

image

To this:

image

Now we get a straight HTTP 200 on both variations of the link.

```
$ curl -I https://stellar-lebkuchen-6a326d.netlify.app/docs/commands/zed/
HTTP/2 200 

$ curl -I https://stellar-lebkuchen-6a326d.netlify.app/docs/commands/zed
HTTP/2 200 
```

I also added config under **Site Settings > Domain Management > Custom Domains** for `testzed.brimdata.io`, which was a prerequisite for the auto-generation of an SSL/TLS cert to have the site served securely when accessed via https://testzed.brimdata.io. Once this PR merges, I'll modify that **Custom Domain** config to point to zed.brimdata.io instead.

image

image

## Docusaurus Config Deltas

While Netlify changes alone got us to a clean link checker run without excessive redirects, with the default `trailingSlash: true` Docusaurus config, clicking the formerly-broken asset links discussed in #26 always resulted in a downloaded filename `download`. Moving to the `trailingSlash: false` config as is done in this PR improves this to where downloaded files from those asset links get filenames `github1-2496d524ce44f4cb9f32cfeb70fa669e.zng` and `github2-d64f82ea518d971a86ad9e81da3a9b6e.zng`, i.e., based on the original filenames in GitHub along with stuff to make it unique. This seems good enough to me.

## Broken Link Checking

Like we do with the www.brimdata.io web site, I went ahead and added a link checker to the deployment Action to quickly catch breakages. You can see in a [recent Action run](https://github.com/brimdata/zed-docs-site/actions/runs/2929059947) that it's running clean against the https://testzed.brimdata.io site.

I similarly wanted to avoid a repeat of what we saw on GitHub Pages in #32 that led to backing out the previous attempt at using `0trailingSlash: false`, so I made a test deployment of the www.brimdata.io web site at https://capable-khapse-fa9d06.netlify.app that has all the doc links in the blog articles pointing at https://testzed.brimdata.io, with the trailing slashes on the links in the blog posts left intact. You can see in [this Actions run](https://github.com/philrz/scratchwiki/runs/8023716331?check_suite_focus=true) that a link checker run against this test site also runs clean.

## Final Steps

Once this PR is approved, final changes before merge:

- [x] Change Docusaurus `url` config parameter back to `https://zed.brimdata.io`
- [x] In `deploy.yaml`, change the triggered branch back to `main` and restore the `repository_dispatch` config
- [x] Point the link checker config at https://zed.brimdata.io

Once the PR Is merged, final changes to migrate the production site:

- [ ] Change the zed.brimdata.io CNAME in our DNS config to point to stellar-lebkuchen-6a326d.netlify.app instead of GitHub Pages
- [ ] Change the **Custom domain** setting in Netlify from testzed.brimdata.io to zed.brimdata.io and ensure the auto-generated SSL/TLS cert works

Post-migration cleanup steps:

- [ ] In GitHub **Settings** for this repo, click **Unpublish site**
- [ ] Share Netlify secrets with the team (put in AWS Secrets Manager?)
- [ ] Keep an eye on bandwidth utilization over time to see if we stay well below the 100 GB/mo limit

### CODE REVIEW

**Comment by mattnibs** [comment]
This all looks good, I'd prefer to review this with all the testzed stuff reverted before hitting approve.

**Comment by philrz** [comment]
@mattnibs: Ok, I've pushed a commit so it's prepped in the final state to act as zed.brimdata.io. Please proceed with review. Thanks!

**Review by mattnibs — APPROVED** [review]

**Comment by philrz** [comment]
Now that several days have passed, I've "unpublished" the site from GitHub Pages. For archival purposes, here's what that **Settings** page looked like before I made the change.

image

**Comment by philrz** [comment]
Here's an update on the bottom checklist item above. I'd been checking the Netlify usage every day and for the first few weeks bandwidth usage remained well below 1 GB, which seemed great. Then a few days ago it spontaneously jumped to 3 GB, which was unexpected, but still way below the 100 GB monthly cap. Checking it today, it's now at 38 GB!

image

I have no idea what may have caused that spike. Maybe some runaway automation or crawler hammered the site excessively. Speaking of which, we did get notification that the Algolia crawler that powers the site's Search tool did just run early this  morning, so maybe that's somehow related, though it's hard to imagine why that would cause such excessive bandwidth usage. Anyway, we're still less than 50% to the limit and the Netlify docs indicate we should get a notification before we hit any hard caps, so I'm prepared to watch this play out. But maybe at some point we'll just need to invest in one of their paid plans so we never have the embarrassment of quickly hitting a cap when we're not around to respond.

**Comment by philrz** [comment]
Update: After reviewing with the team, we made the decision to go ahead and upgrade to the Pro plan so now our bandwidth cap is 1 TB/month. This upgrade has now been completed, so hopefully we're good to go from here.

**Pull request merged**
